### ISSUE TITLE
An unexpected error occured.

### ISSUE THREAD

**Issue by metacoma** [cathive/concourse-chartmuseum-resource#3]
Hello, I have a trouble with  chartmuseum-resource.
It's reproduces with chartmuseum latest/0.2.7, chartmuseum-resource 0.2.0/latest


Pipeline source:
```
---                                                                                                                                   
resource_types:                                                                                                                       
  - name: chartmuseum                                                                                                                 
    type: docker-image                                                                                                                
    source:                                                                                                                           
      repository: cathive/concourse-chartmuseum-resource                                                                              
      tag: latest                                                                                                                     
                                                                                                                                      
                                                                                                                                      
resources:                                                                                                                            
- name: gerrit                                                                                                                        
  type: git                                                                                                                           
  source:                                                                                                                             
    uri: http://git/gerrit
    branch: master                                                                                                                    
                                                                                                                                      
- name: gerrit-chartmuseum                                                                                                            
  type: chartmuseum                                                                                                                   
  source:                                                                                                                             
    server_url: "http://chartmuseum-chartmuseum.infra:8080/"                                                                          
    chart_name: "gerrit"                                                                                                              
    version_range: "*"                                                                                                                
                                                                                                                                      
jobs:                                                                                                                                 
- name: publish chart                                                                                                                 
  plan:                                                                                                                               
  - get: gerrit                                                                                                                       
    trigger: true                                                                                                                     
  - put: gerrit-chartmuseum                                                                                                           
    params:                                                                                                                           
      chart: gerrit                                                                                                                   
      sign: false                
```


Pipeline fails with:
```
Processing chart at "/tmp/build/put/gerrit"...
Performing "helm package"...
Inspecting chart file: "/tmp/tmp-83H2Kne19liUL/gerrit-0.1.0.tgz"...
Uploading chart file: "/tmp/tmp-83H2Kne19liUL/gerrit-0.1.0.tgz"...


An unexpected error occured.
events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:258:10)
    at Socket.Writable.write (_stream_writable.js:292:21)
    at process.on.err (/usr/local/lib/node_modules/@cathive/concourse-chartmuseum-resource/out.js:296:24)
    at process.emit (events.js:182:13)
    at emitPromiseRejectionWarnings (internal/process/promises.js:105:20)
    at process._tickCallback (internal/process/next_tick.js:69:34)
Emitted 'error' event at:
    at validChunk (_stream_writable.js:261:12)
    at Socket.Writable.write (_stream_writable.js:292:21)
    [... lines matching original stack trace ...]
    at process._tickCallback (internal/process/next_tick.js:69:34)
```

Also, i double checked, chartmuseum-endpoint works correctly and available from concourse container
